















































































































 #include<conio.h>
 #include<stdio.h>
 void show(int,int);

 void main()
 {
 clrscr();
 show(12,12);
  show(129,102);
  getch();
 }

 void show(int a,int b)
 {
 printf("%d\n",(a+b));



 }







